### ISSUE TITLE
Not a `language` object

### ISSUE THREAD

**Issue by syoh** [bartoszukm/SimilaR#1]
I am getting the following error, and I would appreciate any help!

```
> library(SimilaR)
> asdf = SimilaR_fromDirectory('.',fileTypes = 3)
Error in checkPlagiarism_gplag_cpp_list_kernel2_test(parsess, h = 2, sums) : 
  Not a `language` object
```

What could be the source of this error?

**Comment by bartoszukm** [comment]
Every argument is needed. Try:

```
library(SimilaR)
asdf = SimilaR_fromDirectory('.',
                             returnType="data.frame",
                             fileTypes = "function",
                             aggregation="both")
```

For other possible values for arguments, try

```
?SimilaR_fromDirectory
```

**Comment by gagolews** [comment]
"Every argument is needed." -- that's not user-friendly IMO

I think that at the beginning of the function you should call

```
returnType <- match.arg(returnType)
fileTypes <- match.arg(fileTypes)
aggregation <- match.arg(aggregation)
```

this way you get both value-check and default vals for the params

and the same for `SimilaR_fromTwoFunctions()`

**Comment by bartoszukm** [comment]
OK, that's right, I corrected it and it will be a part of the next SimilaR's release
