### ISSUE TITLE
parse error when passing args extracted from a list

### ISSUE THREAD

**Issue by gagolews** [bartoszukm/SimilaR#2]
```
library("SimilaR")

funs <- list(mean, sd) # whatever

SimilaR_fromTwoFunctions(funs[[1]], funs[[2]])


```

yields:

```
Error in parse(text = c(stri_paste(functionNames[[1]], "<-"), deparse(function1))) : 
  <text>:1:1: unexpected '[['
1: [[
```

consider calling `make.names()` on the results returned by `as.character(parse(...))` inside your function

for example::

```
> make.names(c("test", "funs[[1]]", "%op%", "eye<-"))
[1] "test"      "funs..1.." "X.op."     "eye.."   
```

**Comment by gagolews** [comment]
I also think that the `stri_paste(functionNames[[1]], "<-"), deparse(function1))` line could be replaced with:

```
sprintf("`%s` <- %s",  functionNames[[1]], deparse(function1))
```
(note the  acute accent char) -- this could avoid problems with names like `name<-`

**Comment by gagolews** [comment]
also the function could get the `functionNames` argument if a user wants to specify names she likes
(instead of always relying on `substitute()`) -- if `functionNames` are missing, i.e., `missing(functionNames)==TRUE`,  which would be the default, you could rely on the current behavior; otherwise, get the two labels from a given character vector

**Comment by bartoszukm** [comment]
OK, I corrected it, now all of these lines work:

```
f1 <- function(x) {x*x}
f2 <- function(x,y) {x+y}
funs <- list(f1, f2)
`name<-` <- function(x){x*x}

SimilaR_fromTwoFunctions(funs[[1]], funs[[2]])
SimilaR_fromTwoFunctions(f1, f2)
SimilaR_fromTwoFunctions(f1, `name<-`)
SimilaR_fromTwoFunctions(f2, `name<-`)
SimilaR_fromTwoFunctions(f2, `name<-`, functionNames = c("first", "second<-"))
```

**Comment by bartoszukm** [comment]
What is more, there was no need to use

```
sprintf("`%s` <- %s",  functionNames[[1]], deparse(function1))
```

as before this line I call `make.names()` so `<-` is replaced with `..`

**Comment by gagolews** [comment]
Great,  thanks, all OK

```
> SimilaR_fromTwoFunctions(funs[[1]], funs[[2]])
      name1     name2 SimilaR decision
1 funs..1.. funs..2..       1        1
> SimilaR_fromTwoFunctions(funs[[1]], funs[[2]], functionNames=c("a", "b"))
  name1 name2 SimilaR decision
1     a     b       1        1
```
